import {
  shopCaro1,
  shopCaro2,
  shopCaro3,
  shopCaro4,
  shopCaro5,
  shopCaro6,
  shopCaro7,
  shopCaro8,
  category1,
  category2,
  category3,
  category4,
  category5,
  category6,
  category7,
  category8,
  category9,

  //menuPage
  burger1,
  burger2,
  burger3,
  burger4,
  burger5,
  burger6,
  burger7,
  burger8,
  drinks1,
  drinks2,
  drinks3,
  drinks4,
  drinks5,
  drinks6,
  drinks7,
  drinks8,
  drinks9,
  drinks10,
  drinks11,
  drinks12,
  drinks13,
  drinks14,
  pizza1,
  pizza2,
  pizza3,
  pizza4,
  pizza5,
  pizza6,
  pizza7,
  pizza8,
  pizza9,
  pizza10,
  pizza11,
  pizza12,
} from "../src/imagesData";

const menuData = [
  //burgers
  {
    id: 1,
    name: "Bacon Burger",
    category: "burger",
    img: burger1,
    rating: 4,
    price: 12.99,
    desc: "A classic burger featuring crispy bacon, lettuce, tomato, and special sauce. Served with golden fries.",
  },
  {
    id: 2,
    name: "Cheese Burger",
    category: "burger",
    img: burger2,
    rating: 4,
    price: 11.49,
    desc: "Delicious cheeseburger topped with cheddar cheese, pickles, onions, and a dollop of tangy mustard.",
  },
  {
    id: 3,
    name: "Chicken Burger",
    category: "burger",
    img: burger3,
    rating: 4,
    price: 10.99,
    desc: "Juicy grilled chicken patty served with lettuce, tomato, and mayo in a soft burger bun.",
  },
  {
    id: 4,
    name: "Country Burger",
    category: "burger",
    img: burger4,
    rating: 4,
    price: 13.79,
    desc: "A taste of the countryside! Meat patty with sautéed mushrooms, Swiss cheese, and tangy BBQ sauce.",
  },
  {
    id: 5,
    name: "Double Meat Burger",
    category: "burger",
    img: burger5,
    rating: 4,
    price: 14.99,
    desc: "Double the meat, double the flavor! Two meat patties, lettuce, cheese, and special sauce.",
  },
  {
    id: 6,
    name: "Double Cheese Burger",
    category: "burger",
    img: burger6,
    rating: 4,
    price: 13.49,
    desc: "Indulge in cheesy goodness! Two layers of cheese on a meat patty with lettuce, tomato, and mayo.",
  },
  {
    id: 7,
    name: "Veggie Burger",
    category: "burger",
    img: burger7,
    rating: 4,
    price: 11.99,
    desc: "A plant-based delight! Grilled veggie patty with fresh lettuce, tomatoes, and vegan mayo.",
  },
  {
    id: 8,
    name: "Pene Salmone Burger",
    category: "burger",
    img: burger8,
    rating: 4,
    price: 15.29,
    desc: "For seafood lovers! Grilled salmon patty with penne pasta, lettuce, and zesty lemon aioli.",
  },

  //drinks here

  {
    id: 9,
    name: "Blueberry Shake",
    category: "drinks",
    img: drinks1,
    rating: 4,
    price: 6.99,
    desc: "Creamy blueberry shake made with fresh blueberries, milk, and a scoop of vanilla ice cream.",
  },
  {
    id: 10,
    name: "Fresh Lime",
    category: "drinks",
    img: drinks2,
    rating: 4,
    price: 4.79,
    desc: "Refreshing lime drink prepared with freshly squeezed lime juice, sugar, and a hint of mint.",
  },
  {
    id: 11,
    name: "Ice Lime Cola",
    category: "drinks",
    img: drinks3,
    rating: 4,
    price: 3.99,
    desc: "Fizzing cola infused with zesty lime flavor, served over ice for a refreshing experience.",
  },
  {
    id: 12,
    name: "Iced Tea",
    category: "drinks",
    img: drinks4,
    rating: 4,
    price: 5.49,
    desc: "Classic iced tea brewed to perfection, served chilled and garnished with a lemon slice.",
  },
  {
    id: 13,
    name: "Iced Tea Bottle",
    category: "drinks",
    img: drinks5,
    rating: 4,
    price: 2.99,
    desc: "Grab a bottled iced tea for on-the-go refreshment, available in various flavors.",
  },
  {
    id: 14,
    name: "Kiwi Smoothie",
    category: "drinks",
    img: drinks6,
    rating: 4,
    price: 7.29,
    desc: "Blended kiwi smoothie made with fresh kiwi fruits, yogurt, and a touch of honey for sweetness.",
  },
  {
    id: 15,
    name: "Lemonade Drink",
    category: "drinks",
    img: drinks7,
    rating: 4,
    price: 6.49,
    desc: "Homemade lemonade crafted with squeezed lemons, sugar, and a splash of sparkling water.",
  },
  {
    id: 16,
    name: "Black Coffee",
    category: "drinks",
    img: drinks8,
    rating: 4,
    price: 3.99,
    desc: "Robust black coffee brewed to perfection, served hot and strong for coffee enthusiasts.",
  },
  {
    id: 17,
    name: "Iced Coffee",
    category: "drinks",
    img: drinks9,
    rating: 4,
    price: 4.49,
    desc: "Chilled iced coffee made with freshly brewed coffee, milk, and a hint of sweet syrup.",
  },
  {
    id: 18,
    name: "Pizzaro Coffee",
    category: "drinks",
    img: drinks10,
    rating: 4,
    price: 5.99,
    desc: "Specialty coffee featuring rich espresso, frothy milk, and a dusting of cocoa powder on top.",
  },
  {
    id: 19,
    name: "Plain Tea",
    category: "drinks",
    img: drinks11,
    rating: 4,
    price: 2.49,
    desc: "Simple and soothing plain tea served hot, perfect for a relaxing moment.",
  },
  {
    id: 20,
    name: "Soda Bottle",
    category: "drinks",
    img: drinks12,
    rating: 4,
    price: 1.99,
    desc: "Chilled soda in a bottle, available in various flavors to quench your thirst.",
  },
  {
    id: 21,
    name: "Strawberry Shake",
    category: "drinks",
    img: drinks13,
    rating: 4,
    price: 6.79,
    desc: "Indulge in a delightful strawberry shake made with fresh strawberries, milk, and creamy ice cream.",
  },
  {
    id: 22,
    name: "Strawberry Tea",
    category: "drinks",
    img: drinks14,
    rating: 4,
    price: 3.49,
    desc: "Flavorful strawberry tea brewed with tea leaves and infused with natural strawberry essence.",
  },
  {
    id: 23,
    name: "Cappuccino",
    category: "drinks",
    img: drinks14,
    rating: 4,
    price: 4.99,
    desc: "Classic cappuccino topped with equal parts of espresso, steamed milk, and foamy milk froth.",
  },
  {
    id: 24,
    name: "Tropicana Juice",
    category: "drinks",
    img: "tropicana_juice.jpg",
    rating: 4,
    price: 5.79,
    desc: "Fresh Tropicana juice made from a blend of tropical fruits, packed with vitamins and natural goodness.",
  },
  {
    id: 25,
    name: "Water Bottle",
    category: "drinks",
    img: "water_bottle.jpg",
    rating: 4,
    price: 1.49,
    desc: "Stay hydrated with our bottled water, sourced from natural springs for pure and refreshing taste.",
  },
  {
    id: 26,
    name: "Grilled Chicken Breast",
    category: "chicken",
    img: "grilled_chicken.jpg",
    rating: 4,
    price: 15.99,
    desc: "Tender and succulent grilled chicken breast marinated in herbs and spices, served with roasted vegetables.",
  },
  {
    id: 27,
    name: "Spicy Chicken Wings",
    category: "chicken",
    img: "spicy_chicken_wings.jpg",
    rating: 4,
    price: 13.49,
    desc: "Crispy and spicy chicken wings tossed in a flavorful sauce, perfect for sharing with friends.",
  },
  {
    id: 28,
    name: "Chicken Alfredo",
    category: "chicken",
    img: "chicken_alfredo.jpg",
    rating: 4,
    price: 14.99,
    desc: "Creamy chicken Alfredo pasta with tender chunks of chicken, fettuccine, and a rich Alfredo sauce.",
  },
  {
    id: 29,
    name: "Honey Mustard Chicken",
    category: "chicken",
    img: "honey_mustard_chicken.jpg",
    rating: 4,
    price: 12.79,
    desc: "Sweet and tangy honey mustard-glazed chicken, served with a side of rice and steamed vegetables.",
  },
  {
    id: 30,
    name: "Lemon Herb Roasted Chicken",
    category: "chicken",
    img: "lemon_herb_roasted_chicken.jpg",
    rating: 4,
    price: 15.29,
    desc: "Roasted chicken infused with zesty lemon and aromatic herbs, accompanied by roasted potatoes.",
  },
  {
    id: 31,
    name: "Chicken Stir-Fry",
    category: "chicken",
    img: "chicken_stir_fry.jpg",
    rating: 4,
    price: 13.79,
    desc: "A vibrant chicken stir-fry loaded with colorful vegetables and a savory stir-fry sauce.",
  },
  {
    id: 32,
    name: "BBQ Chicken Drumsticks",
    category: "chicken",
    img: "bbq_chicken_drumsticks.jpg",
    rating: 4,
    price: 11.99,
    desc: "Smoky and tender BBQ chicken drumsticks, served with coleslaw and cornbread.",
  },
  {
    id: 33,
    name: "Crispy Chicken Tenders",
    category: "chicken",
    img: "crispy_chicken_tenders.jpg",
    rating: 4,
    price: 10.99,
    desc: "Golden and crispy chicken tenders with a side of dipping sauces, a family favorite.",
  },
  {
    id: 34,
    name: "Teriyaki Chicken Bowl",
    category: "chicken",
    img: "teriyaki_chicken_bowl.jpg",
    rating: 4,
    price: 13.99,
    desc: "Savory teriyaki chicken served over steamed rice with broccoli and sesame seeds.",
  },
  {
    id: 35,
    name: "Butter Chicken",
    category: "chicken",
    img: "butter_chicken.jpg",
    rating: 4,
    price: 12.99,
    desc: "Creamy and rich butter chicken curry served with naan bread or steamed rice.",
  },
  {
    id: 36,
    name: "Margherita Pizza",
    category: "pizza",
    img: pizza1,
    rating: 4,
    price: 12.99,
    desc: "Classic Margherita pizza topped with tomato sauce, fresh mozzarella cheese, basil, and a drizzle of olive oil.",
  },
  {
    id: 37,
    name: "Pepperoni Pizza",
    category: "pizza",
    img: pizza2,
    rating: 4,
    price: 14.99,
    desc: "Traditional pepperoni pizza featuring zesty pepperoni slices, tomato sauce, and melted mozzarella cheese.",
  },
  {
    id: 38,
    name: "Vegetarian Pizza",
    category: "pizza",
    img: pizza3,
    rating: 4,
    price: 13.79,
    desc: "Hearty vegetarian pizza loaded with colorful bell peppers, mushrooms, olives, onions, and cheese.",
  },
  {
    id: 39,
    name: "Hawaiian Pizza",
    category: "pizza",
    img: pizza4,
    rating: 4,
    price: 14.49,
    desc: "Sweet and savory Hawaiian pizza with ham, pineapple chunks, tomato sauce, and mozzarella cheese.",
  },
  {
    id: 40,
    name: "BBQ Chicken Pizza",
    category: "pizza",
    img: pizza5,
    rating: 4,
    price: 15.29,
    desc: "Tangy BBQ chicken pizza featuring BBQ sauce, grilled chicken, red onions, and cilantro on a crispy crust.",
  },
  {
    id: 41,
    name: "Meat Lover's Pizza",
    category: "pizza",
    img: pizza6,
    rating: 4,
    price: 16.99,
    desc: "A carnivore's delight! Loaded with pepperoni, sausage, bacon, ham, and ground beef on a cheesy base.",
  },
  {
    id: 42,
    name: "Mushroom and Olive Pizza",
    category: "pizza",
    img: pizza7,
    rating: 4,
    price: 13.99,
    desc: "Savory pizza topped with fresh mushrooms, black olives, tomato sauce, and a blend of cheeses.",
  },
  {
    id: 43,
    name: "White Pizza",
    category: "pizza",
    img: pizza8,
    rating: 4,
    price: 14.79,
    desc: "Delectable white pizza featuring ricotta cheese, garlic sauce, spinach, and a sprinkle of Parmesan cheese.",
  },
  {
    id: 44,
    name: "Buffalo Chicken Pizza",
    category: "pizza",
    img: pizza9,
    rating: 4,
    price: 15.49,
    desc: "Spicy Buffalo chicken pizza with buffalo sauce, grilled chicken, red onions, and ranch dressing.",
  },
  {
    id: 45,
    name: "Pesto and Tomato Pizza",
    category: "pizza",
    img: pizza10,
    rating: 4,
    price: 14.99,
    desc: "Fresh and flavorful pizza topped with basil pesto, sliced tomatoes, mozzarella cheese, and a drizzle of balsamic glaze.",
  },
  {
    id: 46,
    name: "Four Cheese Pizza",
    category: "pizza",
    img: pizza11,
    rating: 4,
    price: 15.99,
    desc: "A cheese lover's dream! Indulge in a blend of mozzarella, cheddar, provolone, and Parmesan cheeses on a thin crust.",
  },
  {
    id: 47,
    name: "Seafood Delight Pizza",
    category: "pizza",
    img: pizza12,
    rating: 4,
    price: 17.49,
    desc: "Delicious seafood pizza featuring a medley of shrimp, crab, clams, and garlic butter sauce on a crispy crust.",
  },
];

const homeMenuData = [
  // Breakfast category
  {
    id: 61,
    name: "Apricot Chicken",
    category: "breakfast",
    img: "apricot_chicken.jpg",
    rating: 4.5,
    price: 15.99,
  },
  {
    id: 62,
    name: "Pepperoni Calzone",
    category: "breakfast",
    img: "pepperoni_calzone.jpg",
    rating: 3.8,
    price: 12.49,
  },
  {
    id: 63,
    name: "Blueberry Shake",
    category: "breakfast",
    img: "blueberry_shake.jpg",
    rating: 4.2,
    price: 10.99,
  },
  {
    id: 64,
    name: "Fresh Lime",
    category: "breakfast",
    img: "fresh_lime.jpg",
    rating: 4.0,
    price: 11.79,
  },
  {
    id: 65,
    name: "Black Coffee",
    category: "breakfast",
    img: "black_coffee.jpg",
    rating: 4.7,
    price: 9.99,
  },
  {
    id: 66,
    name: "Italiano Original",
    category: "breakfast",
    img: "italiano_original.jpg",
    rating: 4.3,
    price: 13.29,
  },

  // Lunch category
  {
    id: 67,
    name: "Water Bottle",
    category: "lunch",
    img: "water_bottle.jpg",
    rating: 4.9,
    price: 10.49,
  },
  {
    id: 68,
    name: "Vegge Lover",
    category: "lunch",
    img: "vegge_lover.jpg",
    rating: 4.4,
    price: 14.99,
  },
  {
    id: 69,
    name: "Tropicana Juice",
    category: "lunch",
    img: "tropicana_juice.jpg",
    rating: 4.6,
    price: 11.79,
  },
  {
    id: 70,
    name: "Trio Cheese",
    category: "lunch",
    img: "trio_cheese.jpg",
    rating: 4.1,
    price: 13.49,
  },
  {
    id: 71,
    name: "Trio Cafe",
    category: "lunch",
    img: "trio_cafe.jpg",
    rating: 4.3,
    price: 12.99,
  },
  {
    id: 72,
    name: "Tagliatelle Molto",
    category: "lunch",
    img: "tagliatelle_molto.jpg",
    rating: 4.7,
    price: 15.59,
  },

  // Dinner category
  {
    id: 73,
    name: "Supreme Pizza",
    category: "dinner",
    img: "supreme_pizza.jpg",
    rating: 4.8,
    price: 18.99,
  },
  {
    id: 74,
    name: "Double Cheese",
    category: "dinner",
    img: "double_cheese.jpg",
    rating: 4.5,
    price: 16.49,
  },
  {
    id: 75,
    name: "Iced Tea",
    category: "dinner",
    img: "iced_tea.jpg",
    rating: 4.2,
    price: 12.99,
  },
  {
    id: 76,
    name: "Tropicana Juice",
    category: "dinner",
    img: "tropicana_juice_dinner.jpg",
    rating: 4.6,
    price: 11.79,
  },
  {
    id: 77,
    name: "Molto Tagliatelle",
    category: "dinner",
    img: "molto_tagliatelle.jpg",
    rating: 4.4,
    price: 14.29,
  },
  {
    id: 78,
    name: "Mix Pasta",
    category: "dinner",
    img: pizza1,
    rating: 4.3,
    price: 13.79,
  },
];

const shopCaro = [
  {
    id: 51,
    name: "Bolognese Pasta",
    rating: 4,
    desc: "Savor the Italian classic with our Bolognese Pasta! A hearty meaty sauce, garnished with Parmesan perfection.",
    price: 15.99,
    img: shopCaro1,
  },
  {
    id: 52,
    name: "Loaded Veg Pizza",
    rating: 3,
    desc: "Craving veggies? Dive into our Loaded Veg Pizza! A crispy crust generously topped with vibrant veggies, cheese, and zesty sauce for a veggie lover's dream.",
    price: 18.49,
    img: shopCaro2,
  },
  {
    id: 53,
    name: "Black Coffee",
    rating: 5,
    desc: "Kick-start your day with the simplicity of Black Coffee! Bold, aromatic, and robust, this pure brew offers a wake-up call in every energizing sip.",
    price: 3.99,
    img: shopCaro3,
  },
  {
    id: 54,
    name: "Kiwi Smoothie",
    rating: 4,
    desc: "Embrace freshness with our Kiwi Smoothie! Blended to perfection, it's a vibrant concoction of ripe kiwis, yogurt, and a hint of sweetness—a refreshing tropical escape.",
    price: 5.79,
    img: shopCaro4,
  },
  {
    id: 55,
    name: "Bacon Burger",
    rating: 4,
    desc: "Savor the sizzle with our bacon burgers! Indulge in crispy bacon, juicy patties, and gourmet toppings. A taste explosion awaits!",
    price: 10.95,
    img: shopCaro5,
  },
  {
    id: 56,
    name: "Blueberry Shake",
    rating: 3,
    desc: "Experience bliss in a glass with our Blueberry Shake! Creamy goodness meets the burst of fresh blueberries for a delightful treat.",
    price: 8.99,
    img: shopCaro6,
  },
  {
    id: 57,
    name: "BBQ Chicken Breast",
    rating: 4,
    desc: "Dive into savory perfection with our BBQ Chicken Breast! Juicy, grilled to perfection, smothered in rich barbecue sauce for unbeatable flavor.",
    price: 15.68,
    img: shopCaro7,
  },
  {
    id: 58,
    name: "Chocolate Cake",
    rating: 3,
    desc: "Indulge your senses with our decadent Chocolate Cake! Moist layers of rich cocoa, luscious frosting—every bite a heavenly cocoa celebration!",
    price: 11.99,
    img: shopCaro8,
  },
];

const category = [
  {
    id: 1,
    img: category1,
    name: "COMBO",
    bg: "bg-[#FFBA00]",
    products: 9,
  },
  {
    id: 2,
    img: category2,
    name: "KIDS MENU",
    bg: "bg-[#F37B2A]",
    products: 5,
  },
  {
    id: 3,
    img: category8,
    name: "PIZZA",
    bg: "bg-[#CC3433]",
    products: 20,
  },
  {
    id: 4,
    img: category4,
    name: "BOX MEALS",
    bg: "bg-[#0096DC]",
    products: 6,
  },
  {
    id: 5,
    img: category6,
    name: "BURGER",
    bg: "bg-[#F37B2A]",
    products: 14,
  },
  {
    id: 6,
    img: category3,
    name: "CHICKEN",
    bg: "bg-[#824235]",
    products: 7,
  },
  {
    id: 7,
    img: category7,
    name: "SAUCES",
    bg: "bg-[#F37B2A]",
    products: 13,
  },
  {
    id: 8,
    img: category5,
    name: "DRINKS",
    bg: "bg-[#C31162]",
    products: 11,
  },
  {
    id: 9,
    img: category9,
    name: "All Products",
    bg: "bg-[#293134]",
    products: 78,
  },
];

export { menuData, homeMenuData, shopCaro, category };
